# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.8-slim

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# copy necessary components
COPY dashboard dashboard/
COPY lib lib/

# Install requirements
RUN python -m pip install -r dashboard/requirements.txt

# Add lib directory to PYTHONPATH
ENV PYTHONPATH=/app/lib:/app/dashboard

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
CMD ["python", "-m", "gunicorn", "rundashboard:server", "-b", ":8050"]